import pandas as pd
import matplotlib.pyplot as plt

zx=pd.read_csv("data.csv")
counts=zx["Type1"].value_counts()
plt.bar(counts.index,counts.values)
plt.title("Pokemons for Type1") 
plt.xlabel("Types")
plt.ylabel("Count")
plt.show()
plt.scatter(zx["Height"],zx["Weight"])
plt.title("Pokemon Weight Height")
plt.xlabel("Height")
plt.ylabel("Weight")
plt.show()
zc=zx["Legendary"].value_counts()
plt.pie(zc.values,labels=["Non-Legendary","Legendary"],autopct="%1.1f%%")
plt.title("Legendary and Non-Legendary")
plt.show()
plt.hist(zx["Weight"],bins=30)
plt.title("Pokemon Weight Distribution")
plt.xlabel("Weight")
plt.ylabel("Count")
plt.show()